### ISSUE TITLE
Block Play Pause Issue

### ISSUE THREAD

**Issue by andyluak** [WPChill/strong-testimonials#230] opened 2021-03-12 10:55 UTC
**Describe the bug**
Pause play button are not working. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/49715292/110930742-28bcd700-8332-11eb-8a80-1d410ee77dc0.png)

1. Create a view
2. Add testimonials
3. Select slideshow with : 
![image](https://user-images.githubusercontent.com/49715292/110930835-3ffbc480-8332-11eb-8f5f-1f068b30fd9a.png)

**Comment by TeoAlex** [comment] 2023-09-07 12:36
Could not reproduce the issue. May have been fixed in a previous update.

**Closed** 2023-09-15 11:51 UTC
Labels: bug, need testing
